### ISSUE TITLE
Buildkite Integration Fails with 404 - API Endpoint Not Found

### ISSUE THREAD

**Issue by BanerjeeAgniva** [buildkite/backstage-plugin#65]
**Description:**

While integrating Buildkite with the Backstage catalog, we encountered a `404 Not Found` error when attempting to fetch pipeline/build data.

**Steps to Reproduce:**

1. Entity is defined in Backstage with the following annotation:

   ```yaml
   buildkite.com/project-slug: agniva/demokite
   ```
2. The Backstage frontend attempts a GET request to:

   ```
   https://<internal-host>/idp/api/proxy/buildkite/api/
   ```
3. This request returns a `404 Not Found` error.
4. UI displays:

   ```
   failed to fetch data, status 404
   ```

5. Plugin Config:

```
  proxy:
    endpoints:
      '/buildkite/api':
        target: https://api.buildkite.com/v2
        headers:
          Authorization: Bearer ${BUILDKITE_API_TOKEN}
          Accept: application/json
        allowedHeaders: ['Authorization']
        pathRewrite:
          '^/api/proxy/buildkite/api' : ''
  buildkite:
    apiToken: ${BUILDKITE_API_TOKEN}
    organization: agniva
```

**Request Details:**

* **Request URL:** `https://<internal-host>/idp/api/proxy/buildkite/api/`
* **Status Code:** `404 Not Found`
* **Request Method:** `GET`
* **Response Headers:**

  ```json
  {
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Allow-Origin": "https://deveshharness.pr2.harness.io",
    "Content-Type": "application/json; charset=utf-8"
  }
  ```

**Expected Behavior:**

The Buildkite proxy endpoint should correctly fetch the build data for the specified project slug without returning a 404 error.

**Screenshots:**

<img width="969" alt="Image" src="https://github.com/user-attachments/assets/f096e7ec-4d3b-4b15-be94-f64e6c9d3bd0" />

<img width="486" alt="Image" src="https://github.com/user-attachments/assets/ddf88948-2376-4c85-8a3a-0e892bae3a2c" />
